/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "sr04.h"
#include "uart.h"
#include "timer.h"
#include "scan.h"

int main(void) {
	TIM2_init();
	TIM4_PWM_PB6_init();
	USART2_init();
	USART2_DMA_init();
	SR04_init();

	while (1) {
	    SCAN_TASK();
	    SR04_TASK();
	}
}
